---
contentdir: "content"
layoutdir: "layouts"
publishdir: "public"
indexes:
  category: "categories"
baseurl: "https://angelluismula.github.io"
title: "Blog personal de Ángel Luis Mula"
# Language
languageCode: "es-ES"
metaDataFormat: "yaml"
theme: "hyde-y"

# Pagination
paginate: 10
paginatePath: "page"

# Enable Disqus integration
disqusShortname: "angelluismula-github-io"

permalinks:
    post: "/:year/:month/:day/:slug/"
    code: "/:slug/"
taxonomies:
    tag: "tags"
    topic: "topics"

author:
    name: "Ángel Luis Mula"
    email: "almula@gmail.com"

    # Sidebar position
    # false, true, "left", "right"
sidebar: "right"

    # Text for the top menu link, which goes the root URL for the site.
    # Default (if omitted) is "Home".
home: "home"

    # Select a syntax highight.
    # Check the static/css/highlight directory for options.
highlight: "default"

    # Sidebar social links.
github = "angelluismula" # Your Github profile ID
linkedin = "angel-luis-mula-jordan-9402345a" # Your LinkedIn profile ID (from public URL)
twitter = "angelluismula" # Your Twitter profile ID
rss = true

blackfriday:
    angledQuotes: true
    fractions: false
    hrefTargetBlank: false
    latexDashes: true
    plainIdAnchors: true
    extensions: []
    extensionmask: []
canonifyurls: true
...